# Generated by Django 2.2 on 2019-09-30 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0006_auto_20190928_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=[django.db.models.deletion.SET_NULL], to=settings.AUTH_USER_MODEL),
        ),
    ]
