# Generated by Django 2.2 on 2019-10-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_auto_20191001_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
